# Generated by Django 5.1 on 2024-08-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='details',
            new_name='detail',
        ),
        migrations.AlterField(
            model_name='react',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
